download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", destfile="data.zip")
unzip ("data.zip", exdir = ".")
ori_data<-read.table("household_power_consumption.txt", header=TRUE, sep=";")
data<-ori_data[which(ori_data$Date=="1/2/2007"|ori_data$Date=="2/2/2007"),]
data$Date<-as.Date(data$Date,format="%d/%m/%Y")
data$datetime <- paste(data$Date, data$Time)
data$datetime <- strptime(data$datetime, format = "%Y-%m-%d %H:%M:%S")
plot(data$datetime,as.numeric(data$Global_active_power), type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.copy(png, file="plot2.png", width=480, height=480)
dev.off()